### Reset endpoint
post http://localhost:8080/admin/reset

### Validate chirp endpoint - Valid

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This is an opinion I need to share with the world"
}

### Validate chirp endpoint - Too long

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This is an opinion I need to share with the world This is an opinion I need to share with the world This is an opinion I need to share with the world This is an opinion I need to share with the world This is an opinion I need to share with the world This is an opinion I need to share with the world"
}

### Validate chirp endpoint - Invalid body field

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body_lolwut": ""
}

### Validate chirp endpoint - Profanity, testing with a bad word

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This is a kerfuffle opinion I need to share with the world"
}

### Validate chirp endpoint - Profanity, testing with no bad word

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "I had something interesting for breakfast"
}

### Validate chirp endpoint - Profanity, testing with a bad word + extra field

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "I hear Mastodon is better than Chirpy. sharbert I need to migrate",
  "extra": "this should be ignored"
}

### Validate chirp endpoint - Profanity, testing with two bad words

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "I really need a kerfuffle to go to bed sooner, Fornax !"
}

### Create new user

post http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "bob@houle5.com"
}

### Create new chirp

post http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "If you're committed enough, you can make any story work.",
  "userId": "bb7bc677-d087-4a82-abf9-5247bd6b690c"
}