### Reset endpoint
post http://localhost:8080/admin/reset

### Validate chirp endpoint - Valid

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This is an opinion I need to share with the world"
}

### Validate chirp endpoint - Too long

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This is an opinion I need to share with the world This is an opinion I need to share with the world This is an opinion I need to share with the world This is an opinion I need to share with the world This is an opinion I need to share with the world This is an opinion I need to share with the world"
}

### Validate chirp endpoint - Invalid body field

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body_lolwut": ""
}

### Validate chirp endpoint - Profanity, testing with a bad word

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This is a kerfuffle opinion I need to share with the world"
}

### Validate chirp endpoint - Profanity, testing with no bad word

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "I had something interesting for breakfast"
}

### Validate chirp endpoint - Profanity, testing with a bad word + extra field

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "I hear Mastodon is better than Chirpy. sharbert I need to migrate",
  "extra": "this should be ignored"
}

### Validate chirp endpoint - Profanity, testing with two bad words

post http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "I really need a kerfuffle to go to bed sooner, Fornax !"
}

### Create new user

post http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "bob@houle10.com",
  "password": "123456"
}

### Create new chirp

post http://localhost:8080/api/chirps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIzZDI2MDNjYy1lZDc5LTRhNDktYjNhMy1jNWMxOTAwOTg5NDEiLCJpYXQiOjE3NjU5MzM5MzYsImV4cCI6MzUzMTg3MTQ3Mn0.eEwjDZc1E3THsiBiHsxK-AhYwHalTqY0gMTO51EPQQA

{
  "body": "If you're committed enough, you can make any story work even more more."
}

### Get all chirps

get http://localhost:8080/api/chirps
Content-Type: application/json

### Get a specific chirp (found)

get http://localhost:8080/api/chirps/69e3e49b-90c7-4b8e-a102-f940e346fa88
Content-Type: application/json

### Get a specific chirp (not found)

get http://localhost:8080/api/chirps/baeae870-6927-42f6-b13a-6e6b03fd8407
Content-Type: application/json

### Login

post http://localhost:8080/api/login
Content-Type: application/json

{
  "password": "123456",
  "email": "bob@houle10.com"
}

### Healthz

get http://localhost:8080/api/healthz
Content-Type: application/json